# FROM python:3.12-slim

# WORKDIR /app

# COPY app/requirements.txt .

# RUN pip install --no-cache-dir -r requirements.txt

# COPY app/ .

# EXPOSE 8000

# CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]

FROM python:3.12-slim

WORKDIR /project

COPY app/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app

RUN mkdir -p logs

EXPOSE 8000

CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]